=== usnistgov/xml-util/src/test/resources/xsd/Person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:include schemaLocation="Commons.xsd"/>

<xs:element name="List">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Person" type="PersonType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:complexType name="AddressType">
    <xs:sequence>
        <xs:element name="Line1" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Line2" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="ZipCode" type="xs:string" minOccurs="1" maxOccurs="1" default="20878"/>
        <xs:element name="State" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="PersonType">
    <xs:sequence>
        <xs:element name="Address" type="AddressType" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="FullName" type="NonEmptyString" use="required"/>
    <xs:attribute name="Role" type="xs:string" default="User"/>
</xs:complexType>

</xs:schema>

=== usnistgov/xml-util/src/test/resources/xsd/People.xml
<?xml version="1.0" encoding="UTF-8"?>
<List 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/home/malick/projects/nist/xml-util/src/main/resources/Person.xsd">
    
    <Person FullName="John Doe">
        <Address>
            <Line1>100 Bureau Dr.</Line1>
            <ZipCode></ZipCode>
            <State>MD</State>
        </Address>
    </Person>
    
    <Person FullName="Foo" Role="Admin">
        <Address>
            <Line1>100 Bureau Dr.</Line1>
            <ZipCode></ZipCode>
            <State>MD</State>
        </Address>
    </Person>
    
</List>
